### ISSUE TITLE
Build error on iOS

### ISSUE THREAD

**Issue by mjafartp** [PurpleSoftSrl/sumup_flutter_plugin#12]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/sumup-0.2.2/ios/Classes/SwiftSumupPlugin.swift:2:8: error: no such module 'SumUpSDK'
    import SumUpSDK
           ^

**Comment by sstasi95** [comment]
Hi,
You probably need a `flutter clean` and a `pod install`.
