### ISSUE TITLE
Fatal error and app crash

### ISSUE THREAD

**Issue by jacopofranza** [PurpleSoftSrl/sumup_flutter_plugin#13]
Hello, I'm occurring in a fatal error with app crash if I close the Sumup bottom sheet when there is the selection for terminal vs payment link.

`[connection] nw_endpoint_handler_set_adaptive_read_handler [C9.1 104.18.16.137:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C9.1 104.18.16.137:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
SUMUP SDK WARNING: tipAmount <= 0 will be ommitted. Tip amount will be reset to nil.
sumup/SwiftSumupPlugin.swift:79: Fatal error: Unexpectedly found nil while unwrapping an Optional value
sumup/SwiftSumupPlugin.swift:79: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001a70b7060 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x1a70b7060 <+0>: ret    
libswiftCore.dylib`_swift_reportToDebugger:
    0x1a70b7064 <+0>: b      0x1a70b7060               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x1a70b7068 <+0>: adrp   x8, 324407
    0x1a70b706c <+4>: ldrb   w0, [x8, #0xfd1]
Target 0: (Runner) stopped.
Lost connection to device.`

**Comment by sstasi95** [comment]
Fixed in 0.2.5
