### ISSUE TITLE
Android build error when including in pubspec.yaml

### ISSUE THREAD

**Issue by palkerecsenyi** [PurpleSoftSrl/sumup_flutter_plugin#15]
This plugin causes a build error on Android when simply being included in pubspec.yaml, without any other changes being made to my project:

```
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.threeten.bp.Clock found in modules jetified-threetenbp-1.4-no-tzdb.2-no-tzdb (org.threeten:threetenbp:1.4.2) and jetified-threetenbp-1.4.2 (org.threeten:threetenbp:1.4.2)
   > ... (hundreds of similar errors)
```

My `minSdkVersion` is 24, above the 21 required in the README file.

**Comment by sstasi95** [comment]
Hi,

it's a problem with your gradle config, try with the suggestions [here](https://stackoverflow.com/questions/60542394/duplicated-classes-found-in-modules-classes) or [here](https://stackoverflow.com/questions/56029393/why-im-getting-duplicate-class-when-running-my-android-project/56029604#56029604) or [here](https://github.com/JakeWharton/ThreeTenABP/issues/117) and let me know if it works.

Simone
