### ISSUE TITLE
Localizing the screens

### ISSUE THREAD

**Issue by ot-repo** [PurpleSoftSrl/sumup_flutter_plugin#19]
Hello,

first of all thank you for the great plugin.

I have a question about the localisations. Login or checkout screens will be shown in english. How can we make these screens appear in German for example?

Thanks in advance!

**Comment by sstasi95** [comment]
Hi,

I think it's not possible, try to follow this [issue](https://github.com/sumup/sumup-android-sdk/issues/30).

Simone
