### ISSUE TITLE
What Model works with this API

### ISSUE THREAD

**Issue by DroneMesh** [PurpleSoftSrl/sumup_flutter_plugin#21]
Hi, 

We are looking to integrate a new payment gateway with API capabilities for our platform. However, I am confused about witch models actually support this SDK.

Is this SDK going to be sending the information over Bluetooth to the device or some sort of local WebSocket will be used?

Thank you

**Comment by sstasi95** [comment]
HI,

This plugin connects to SumUp terminals using bluetooth. For more info check SumUp native SDK repos ([here](https://github.com/sumup/sumup-ios-sdk) for iOS and [here](https://github.com/sumup/sumup-android-sdk) for Android)
