### ISSUE TITLE
Offer loginWithCredentials

### ISSUE THREAD

**Issue by rivella50** [PurpleSoftSrl/sumup_flutter_plugin#29]
I would like to discuss a new login variant `loginWithCredentials` which allows to pass the credentials from the Flutter app (e.g. by storing them in shared preferences) instead of relying on the autofill method when a user has already entered his credentials once in the login form.
Since `loginWithToken` only seems to work for merchants but not for employees this would be a nice addition to this plugin, where a user could enter his credentials once in the app.

What do you think?

**Comment by sstasi95** [comment]
I agree that it would be a nice addition to the plugin, but it has first to be implemented in the SumUp native SDKs before we can add it to the plugin. You can open an issue [here](https://github.com/sumup/sumup-ios-sdk/issues) for iOS and [here](https://github.com/sumup/sumup-android-sdk/issues) for Android.

**Comment by rivella50** [comment]
Thank you for your response. @sstasi95 .
I've found another solution: Allowing the user to perform the SumUp Login as a separate action (i.e. without a payment involved), which then stores the credentials for the login form for future payments.
