### ISSUE TITLE
When adding sumup to pubspec.yaml orientation gets forced into landscape mode

### ISSUE THREAD

**Issue by Silv4n** [PurpleSoftSrl/sumup_flutter_plugin#3]
Hello guys

I just found out, that when adding sumup to my dependencies in pubspec.yaml, the screen gets forced into landscape mode as soon as the app starts. Im building for android, I don't know, if this also happens on iOS.
Sumup package version: 0.2.0

Thanks!

Edit: just looked over the code, probably has something to do with: https://github.com/PurpleSoftSrl/sumup_flutter_plugin/blob/df02fb10a85c96ca3bfd307c71f7b6e067fc3d37/android/src/main/kotlin/io/purplesoft/sumup/SumupPlugin.kt#L51

**Comment by sstasi95** [comment]
Hi @Silv4n,

this is fixed in 0.2.1, thanks for you feedback!

Simone
