### ISSUE TITLE
Error on payment link (iOS)

### ISSUE THREAD

**Issue by ghi8GPA** [PurpleSoftSrl/sumup_flutter_plugin#30]
Hi,
first of all I want to thank you so much for this plugin!

I found a bug when trying to pay through Payment link on iOS:
- on payment link, as we are processing an online payment, card is empty, and so we need to add a null safe, otherwise the app crashes:
![Screenshot 2022-11-30 at 18 22 59](https://user-images.githubusercontent.com/102041876/204865796-49a4a5d2-00ae-491c-8f45-1dcabc70ce05.png)
- on payment link, checkoutResult.additionalInfo?["installments"] is returned, but its type is string and so on dart side the code breaks (SumupPluginCheckoutResponse.dart): 
- 
![Screenshot 2022-11-30 at 18 25 09](https://user-images.githubusercontent.com/102041876/204866300-cbee8651-b383-45c4-b917-217a3451d5a3.png)

I have not yet tried the functionality on Android devices.

Thanks!

**Comment by ghi8GPA** [comment]
For the second issue che correct fix is defaulting instalments to an integer instead of an empty string (line 95 of SwiftSumupPlugin)

**Comment by sstasi95** [comment]
Hi,

Thank you for finding the issues and the solutions. Unfortunately at the moment I'm unable to test them because our SumUp terminal is broken and we're waiting for the replacement.

I'll be back here as soon as I'm able to debug the issues, hopefully in a few weeks.

**Comment by mahmoudalaa97** [comment]
I have a question about the payment response did you change the amount from **double** to **String** in your new API, now I have the issue in my app production when I trace the scenario I found a change **amount type**

**Comment by sstasi95** [comment]
Hi @ghi8GPA,

In the latest SumUp iOS release, they dropped support for Payment Links. [Here's](https://github.com/sumup/sumup-ios-sdk/blob/master/CHANGELOG.md) the changelog.

So, I think we can close this issue.
