### ISSUE TITLE
Cover Android 12 & 13 in the example app

### ISSUE THREAD

**Issue by rivella50** [PurpleSoftSrl/sumup_flutter_plugin#31]
Today i've tested my Flutter app with an Android 13 device and got this error message:
```
Fatal Exception: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@80b0b746: GattService registerScanner
```
Below Android 12 no permission was needed in order to use the SumUp package.
I would like to know what permissions are needed to set in AndroidManifest.xml for using SumUp successfully?
I started using these 4 permissions:
```
<uses-permission android:name="android.permission.BLUETOOTH"
                 android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
                 android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```
Also it would be great if you could update the package's example app regarding the Android part in order to reflect working on Android 12 & 13 as well.

Thank you very much.

EDIT: From what i understand is that the app crashes even if BLUETOOTH_SCAN and BLUETOOTH_CONNECT are defined, since those declarations do not lead to the allowance of accessing nearby devices. Only if i allow that permission manually in the app's permission settings i can use and pay with the SumUp device on an Android 13 device.

**Comment by sstasi95** [comment]
Hi,

Thank you for the issue. I was able to reproduce it trying to connect to a terminal, and upgrading the SumUp sdk seems to fix the issue.
I'm not publishing an update on pub.dev yet, because I can't test the whole payment flow since our SumUp terminal is broken (we're waiting for the replacement).

Could you please try the latest plugin version on git and let me know if it really works? You can do it by adding this to your pub pubspec.yaml:
```yaml
sumup: 
  git: 
    url: https://github.com/PurpleSoftSrl/sumup_flutter_plugin.git
```

Thanks,

Simone

**Comment by rivella50** [comment]
Hi Simone,

thanks for having a look at it.
This afternoon i was able to fix the problem in my project, by including the flutter package [permission_handler](https://pub.dev/packages/permission_handler) and successfully setting the permission for nearby devices with it.
Actually it's a combination of these permissions in AndroidManifest.xml:
```
<!--Before Android 12 (but still needed location, even if not requested)-->
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
<!--From Android 12-->
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"
    android:usesPermissionFlags="neverForLocation"
    tools:targetApi="s" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```
and requesting those runtime permissions with the package:
```
Permission.location,
Permission.bluetoothScan,
Permission.bluetoothConnect
```
Without using that package i guess it's difficult to reach that goal.
