### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by lcsvcn** [PurpleSoftSrl/sumup_flutter_plugin#40]
<img width="324" alt="Screenshot 2023-06-19 at 13 06 50" src="https://github.com/PurpleSoftSrl/sumup_flutter_plugin/assets/6011385/1de518ab-0fa3-4d05-94e7-ad53920dfcf5">

The user is correct and password too.

**Comment by sstasi95** [comment]
Double check that the affiliate key that you use in `Sumup.init(affiliateKey)` is correct, and that the app's bundle id has been added in your sumup portal.

**Comment by sstasi95** [comment]
Closing
