### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by fbosman** [PurpleSoftSrl/sumup_flutter_plugin#43]
When issuing an init I get the message:
Error: MissingPluginException(No implementation found for method initSDK on channel sumup)
Is there an upgrade needed or something else?

**Comment by sstasi95** [comment]
I think a `flutter pub get` before compiling the app should be enough

**Comment by fbosman** [comment]
I did so and it did not resolve the issue

**Comment by sstasi95** [comment]
Have you tried `flutter clean`?

**Comment by fbosman** [comment]
good idea, but it did not work.
the complete messages:
Error: MissingPluginException(No implementation found for method initSDK on channel sumup)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
packages/flutter/src/services/platform_channel.dart 313:7                     _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>

**Comment by sstasi95** [comment]
Ah ok you're using flutter web, that's the issue. The only supported platforms are iOS and Android as you can see from the pub.dev page.
