### ISSUE TITLE
Type 'String' is not a subtype of type 'int?'

### ISSUE THREAD

**Issue by tnovoselec** [PurpleSoftSrl/sumup_flutter_plugin#47]
Seeing several of these lately. Seems like Sumup sometimes returns `installments` field of `SumupPluginCheckoutResponse` as `String`, and not as `int?`.
Anyone else seeing the same?

**Comment by sstasi95** [comment]
Yes, sometimes `installments` is null and the plugin coalesces it as empty string. It seems to happen randomly, I think there's a bug on SumUp's side. I'll publish a patch soon.

**Comment by sstasi95** [comment]
Published version 0.8.1
