### ISSUE TITLE
Return internal_id

### ISSUE THREAD

**Issue by MathiasBrams** [PurpleSoftSrl/sumup_flutter_plugin#5]
Hey, thanks for making the plugin

Can you also return the internal_id from sumUp for the checkout?

Thanks

**Comment by sstasi95** [comment]
Hi @MathiasBrams,

we already return transactionCode in SumupPluginCheckoutResponse, which is the internal SumUp transaction id.  
Is this the field you are looking for?

Simone

**Comment by MathiasBrams** [comment]
yes it is sorry
