### ISSUE TITLE
Android Runtime (IncompatibleClassChangeError ) for FusedLocationProviderClient

### ISSUE THREAD

**Issue by ShadySamirBakheet** [PurpleSoftSrl/sumup_flutter_plugin#53]
Runtime when Call login function 
`java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~aLsQyx34djnpZQZY8NmTrg==/com.app-SBEeHAYr9zP0HYjw4NI1MA==/base.apk!classes20.dex)`

On my Project, We use Google Navigation, geocoding and geolocator Plugins 

project run smoothly but when call your login function throw this error

**Comment by sstasi95** [comment]
Hi, see #45
