### ISSUE TITLE
ThrowIfNotLoggedIn bug

### ISSUE THREAD

**Issue by MathiasBrams** [PurpleSoftSrl/sumup_flutter_plugin#6]
E/flutter (21836): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast

I get this error on the login check, was also there in the 2.0 version

**Comment by sstasi95** [comment]
Fixed in 0.2.2

**Comment by MathiasBrams** [comment]
thank you
