### ISSUE TITLE
SumUp SDK Issues

### ISSUE THREAD

**Issue by PhillipMahlke-flour** [PurpleSoftSrl/sumup_flutter_plugin#60]
The version of the SumUp SDK currently used (5.0.1), contains an issue, where the sdk cannot search for terminals, if the SumUp Account has disabled the setting "accept payments via Cardterminal" in the SumUp App (Setting not available on the website). This Setting was supposed to only work for the sumup app, not for the sdk, as that setting defeats the whole purpose of the sdk. This was fixed in version 5.0.2 of the sdk. Could the package please be updated to use a newer sdk version?

**Comment by sstasi95** [comment]
Hi, this is fixed in version 0.11.0.
