### ISSUE TITLE
Skip failed screen

### ISSUE THREAD

**Issue by MathiasBrams** [PurpleSoftSrl/sumup_flutter_plugin#7]
Can you make it possible to set skipFailedScreen to true, like you have done with the success screen?

Great plugin btw and thanks for fast replies

**Comment by sstasi95** [comment]
Thank you!

Unfortunately the native SDKs don't expose this functionality, so we can't do it.
You can open an issue here [https://github.com/sumup/sumup-ios-sdk](url) for iOS, and here [https://github.com/sumup/sumup-android-sdk](url) for Android.
