### ISSUE TITLE
init(key) always true

### ISSUE THREAD

**Issue by MathiasBrams** [PurpleSoftSrl/sumup_flutter_plugin#8]
Hello,

No matter what key I use, fx simply "k" in the init(key) method, I always get returned true, as in:
I/flutter ( 9386): Method: initSDK, status: true, message: {initialized: true}

This makes it hard for me to alert my users that the key they set doesn't work. Can you do something about this?

Thank you. And thanks for responding fast in general.

**Comment by sstasi95** [comment]
Hi,

unfortunately the native sdk doesn't check the correctness of the affiliate key on the init method, and after you have initialized the sdk with a wrong key if you try to login with correct credentials the error message is 'Invalid credentials', so I'm afraid i can't do anything about it.

You could open an issue on their repos to see if they can do something.

Simone
