### ISSUE TITLE
Urgent: If you change the applicationid / packagename, it doesn't work

### ISSUE THREAD

**Issue by MathiasBrams** [PurpleSoftSrl/sumup_flutter_plugin#9]
Hello, 

Hope you can help me fast.

If you change the applicationid / packagename, it doesn't work, which means you can't release on playstore where you have to change the package name.

When I try to login after changing, I get the "Event rpcEventLogin - Reason: These login details are not valid. Please check your username and password and try again."

If I change the package names and application id's back to the default, then it works fine.

Please help :-)

**Comment by tiz-sharp** [comment]
Hello @MathiasBrams, you need to setup your applicationid like on https://me.sumup.com/it-it/developers. let us know. we are online.

**Comment by MathiasBrams** [comment]
My mistake sorry.
